---
- name: Create new nat gateway using an allocation-id
  ec2_vpc_nat_gateway:
    region: "{{ ec2_region }}"
    ec2_access_key: "{{ ec2_access_key }}"
    ec2_secret_key: "{{ ec2_secret_key }}"
    state: present
    subnet_id: "{{ public_subnet_id }}"
    allocation_id: "{{ allocation_id }}"
  register: nat_gateway

- name: Set fact Nat Gateways IDs
  set_fact:
    nat_gateway_id: "{{ nat_gateway.nat_gateway_id }}"