apiVersion: v1
kind: Service
metadata:
  name: jira
  annotations:
    external-dns.alpha.kubernetes.io/hostname: jira.external-dns.devopscluster.de.
    external-dns.alpha.kubernetes.io/ttl: 60
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    name: tcp
    targetPort: 8080
  selector:
    app: jira

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jira
spec:
  template:
    metadata:
      labels:
        app: jira
    spec:
      containers:
      - image: cptactionhank/atlassian-jira:latest
        name: jira
        ports:
        - containerPort: 8080
          name: tcp