---
- name: Create IAM role for kubernetes master
  iam:
    iam_type: role
    name: "{{ ec2_instance_profile_name_kube_master }}"
    region: "{{ ec2_region }}"
    ec2_access_key: "{{ ec2_access_key }}"
    ec2_secret_key: "{{ ec2_secret_key }}"
    state: present
    trust_policy:
      Version: '2012-10-17'
      Statement:
      - Action: sts:AssumeRole
        Effect: Allow
        Principal:
          Service: ec2.amazonaws.com

- name: Assign kubernetes-master-policy to IAM role for Kubernetes-Master
  iam_policy:
    iam_type: role
    iam_name: "{{ ec2_instance_profile_name_kube_master }}"
    policy_name: "{{ ec2_instance_profile_name_kube_master }}"
    region: "{{ ec2_region }}"
    ec2_access_key: "{{ ec2_access_key }}"
    ec2_secret_key: "{{ ec2_secret_key }}"
    state: present
    policy_json:
          Version: '2012-10-17'
          Statement:
            - Action: ['ec2:* ']
              Effect: Allow
              Resource: '*'
            - Action: ['elasticloadbalancing:* ']
              Effect: Allow
              Resource: '*'
            - Action: ['route53:* ']
              Effect: Allow
              Resource: '*'
            - Action: ['s3:* ']
              Effect: Allow
              Resource: 'arn:aws:s3:::kubernetes-*'

- name: Create IAM role for kubernetes node
  iam:
    iam_type: role
    name: "{{ ec2_instance_profile_name_kube_node }}"
    region: "{{ ec2_region }}"
    ec2_access_key: "{{ ec2_access_key }}"
    ec2_secret_key: "{{ ec2_secret_key }}"
    state: present
    trust_policy:
      Version: '2012-10-17'
      Statement:
      - Action: sts:AssumeRole
        Effect: Allow
        Principal:
          Service: ec2.amazonaws.com

- name: Assign kubernetes-node-policy to IAM role for Kubernetes-Nodes
  iam_policy:
    iam_type: role
    iam_name: "{{ ec2_instance_profile_name_kube_node }}"
    policy_name: "{{ ec2_instance_profile_name_kube_node }}"
    region: "{{ ec2_region }}"
    ec2_access_key: "{{ ec2_access_key }}"
    ec2_secret_key: "{{ ec2_secret_key }}"
    state: present
    policy_json:
          Version: '2012-10-17'
          Statement:
            - Action: ['s3:* ']
              Effect: Allow
              Resource: 'arn:aws:s3:::kubernetes-*'
            - Action: ['ec2:Describe* ']
              Effect: Allow
              Resource: '*'
            - Action: ['ec2:AttachVolume ']
              Effect: Allow
              Resource: '*'
            - Action: ['ec2:DetachVolume ']
              Effect: Allow
              Resource: '*'
            - Action: ['ecr:GetAuthorizationToken ', 'ecr:BatchCheckLayerAvailability ', 'ecr:GetDownloadUrlForLayer ', 'ecr:GetRepositoryPolicy ', 'ecr:DescribeRepositories ', 'ecr:ListImages ', 'ecr:BatchGetImage'  ]
              Effect: Allow
              Resource: '*'