apiVersion: v1
kind: Service
metadata:
  name: jenkins
  annotations:
    external-dns.alpha.kubernetes.io/hostname: jenkins.external-dns.devopscluster.de.
spec:
  type: LoadBalancer
  ports:
  - port: 80
    name: http
    targetPort: 80
  selector:
    app: jenkins

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jenkins
spec:
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
      - image: jenkins
        name: jenkins
        ports:
        - containerPort: 80
          name: http