---
- name: Set EC2 Image for Ubuntu
  set_fact:
    image: "{{ ec2_image_ubuntu16 }}"
  when: bootstrap_os == 'ubuntu'

- name: Set EC2 Image for CentOS
  set_fact:
    image: "{{ ec2_image_centos }}"
  when: bootstrap_os == 'centos'

- name: Set EC2 Image for CoreOS
  set_fact:
    image: "{{ ec2_image_coreos }}"
  when: bootstrap_os == 'core'

- name: Fail if bootstrap_os is none
  failed_when: bootstrap_os == 'none'


# TODO: Gather Facts about Public Subnet ID