---
- name: Create S3-Bucket on AWS
  s3_bucket:
    name: "{{ aws_s3_bucket_name | replace('s3://', '') }}"
    region: "{{ ec2_region }}"
    ec2_access_key: "{{ ec2_access_key }}"
    ec2_secret_key: "{{ ec2_secret_key }}"
    state: present
    versioning: yes
    tags:
      Name: "{{ aws_s3_bucket_name | replace('s3://', '') }}"
      Stage: "{{ stage }}"