apiVersion: v1
kind: Service
metadata:
  name: bitbucket
  annotations:
    external-dns.alpha.kubernetes.io/hostname: bitbucket.external-dns.devopscluster.de.
    external-dns.alpha.kubernetes.io/ttl: 60
spec:
  type: LoadBalancer
  ports:
  - port: 7990
    name: tcp
    targetPort: 7990
  selector:
    app: bitbucket

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: bitbucket
spec:
  template:
    metadata:
      labels:
        app: bitbucket
    spec:
      containers:
      - image: atlassian/bitbucket-server:latest
        name: bitbucket
        ports:
        - containerPort: 7990
          name: tcp