---
- name: Create VPC Internet Gateway
  ec2_vpc_igw:
    vpc_id: " {{ vpc_id }}"
    region: "{{ ec2_region }}"
    ec2_access_key: "{{ ec2_access_key }}"
    ec2_secret_key: "{{ ec2_secret_key }}"
    state: present
    tags:
      Name: "{{ tag_name_kubernetes_internetgateway }}"
  register: igw
  ignore_errors: yes

- name: Gather facts about a filtered list of Internet Gateways
  ec2_vpc_igw_facts:
    region: "{{ ec2_region }}"
    ec2_access_key: "{{ ec2_access_key }}"
    ec2_secret_key: "{{ ec2_secret_key }}"
    filters:
        "tag:Name": "{{ tag_name_kubernetes_internetgateway }}"
  register: igw_facts

- name: set fact igw_id
  set_fact:
    igw_id: "{{ igw_facts.internet_gateways[0].internet_gateway_id }}"