---
- name: Check if Cluster is running
  command: "kops validate cluster {{ aws_cluster_name }} --state {{ aws_s3_bucket_name }}"
  register: cluster_state
  until: cluster_state.stdout.find('Your cluster {{ aws_cluster_name }} is ready') != -1
  retries: 20
  delay: 60

- name: Create Admin User
  command: "kubectl create -f {{ kubernetes_admin_user_file }}"

- name: Create Cluster-Role-Binding
  command: "kubectl create -f {{ kubernetes_clusterrolebinding_file }}"

- name: Create Kubernetes Dashboard
  command: "kubectl create -f {{ kubernetes_dashboard_file }}"

- name: Create Kubernetes External-DNS
  command: "kubectl create -f {{ kubernetes_external_dns_file }}"
