---
- name: upgrade all packages
  yum:
    name: '*'
    state: latest
    update_cache: yes

- name: install packages
  yum:
    name: "{{ item }}"
    state: installed
  with_items: "{{ packages }}"

- name: install python libraries
  pip:
    name: "{{ item }}"
    state: latest
  with_items: "{{ python_libs }}"

- include_tasks: user.yml