---
- name: Update and upgrade yum packages
  yum:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400

- name: install packages
  yum:
    name: "{{ item }}"
    state: installed
  with_items: "{{ packages }}"

- include_tasks: user.yml

- name: Download Kops binaries
  get_url:
    url: "{{ kops_download_path }}"
    dest: /usr/local/bin/kops
    owner: root
    group: root
    mode: 0755
    force: yes
  become: true

- name: Download Kubectl binaries
  get_url:
    url: "{{ kubectl_download_path }}"
    dest: /usr/local/bin/kubectl
    owner: root
    group: root
    mode: 0755
    force: yes
  become: true