---
- name: List all hosted zones
  route53_facts:
    region: "{{ ec2_region }}"
    ec2_access_key: "{{ ec2_access_key }}"
    ec2_secret_key: "{{ ec2_secret_key }}"
    query: hosted_zone
  register: hosted_zones

- name: debug
  debug:
    var: hosted_zones

- name: set fact public hosted_zone_id
  set_fact:
    public_hosted_zone_id: "{{ item.Id | replace('/hostedzone/', '') }}"
  with_items: "{{ hosted_zones.HostedZones }}"
  when: '"api" in item.name'

- name: set fact private hosted_zone_id
  set_fact:
    private_hosted_zone_id: "{{ hosted_zones.HostedZones[1].Id | replace('/hostedzone/', '') }}"