---
- name: List all hosted zones
  route53_facts:
    region: "{{ ec2_region }}"
    ec2_access_key: "{{ ec2_access_key }}"
    ec2_secret_key: "{{ ec2_secret_key }}"
    query: hosted_zone
  register: hosted_zones

- name: debug hosted_zones
  debug:
    var: hosted_zones

- name: set fact private hosted_zone_id
  set_fact:
    vpc_id: "{{ hosted_zones.HostedZones|map(attribute='Id')|last }}"