---
- import_tasks: gather_facts_vpc.yml
- import_tasks: gather_facts_igw.yml
- import_tasks: gather_facts_subnets.yml
- import_tasks: gather_facts_sg.yml
- import_tasks: gather_facts_elb.yml
- import_tasks: gather_facts_instances.yml