apiVersion: v1
kind: Service
metadata:
  name: helloworld
  annotations:
    external-dns.alpha.kubernetes.io/hostname: rocketchat.devopscluster.de.
    external-dns.alpha.kubernetes.io/ttl: 60
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    name: tcp
    targetPort: 8080
  selector:
    app: helloworld

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: helloworld
spec:
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - image: gcr.io/google-samples/node-hello:1.0
        name: helloworld
        ports:
        - containerPort: 8080
          name: tcp