---
packages:
    - git
    - apt-transport-https
    - ca-certificates
    - curl
    - nano
    - wget
    - python-pip
    - python-netaddr

python_libs:
    - boto
    - boto3
    - botocore
    - awscli

kops_version: 1.8.1
kops_download_path: "https://github.com/kubernetes/kops/releases/download/{{ kops_version }}/kops-linux-amd64"
kubectl_version: v1.9.4
kubectl_download_path: "https://storage.googleapis.com/kubernetes-release/release/{{ kubectl_version }}/bin/linux/amd64/kubectl"