---
###################################
# Variables for AWS
###################################
stage: dev
aws_cluster_name: devopscluster.de
aws_s3_bucket_name: s3://devopsclusterbucket
aws_user: centos
aws_vpc_cidr_block: 10.250.192.0/18
aws_subnet_public:
  - cidr: "10.250.224.0/20"
    availability_zone: eu-central-1a
aws_subnet_private:
  - cidr: "10.250.192.0/20"
    availability_zone: eu-central-1a

ec2_region: eu-central-1
ec2_keypair: mycentoskeypair
ec2_image: ami-337be65c # centos image
ec2_available_zone: eu-central-1a
ec2_node_size: t2.medium
ec2_kube_node_count: 3
ec2_kube_master_count: 3

#kops_state_store: "{{ aws_s3_bucket_name }}/{{ stage }}"
kops_state_store: "{{ aws_s3_bucket_name }}"

kubernetes_version: 1.9.3

tag_name_kubernetes_vpc: "kubernetes-vpc-{{ stage }}-{{ aws_cluster_name }}"
tag_name_kubernetes_internetgateway: "kubernetes-internetgw-{{ stage }}-{{ aws_cluster_name }}"
tag_name_kubernetes_public_subnet: "kubernetes-public-subnet-{{ stage }}-{{ aws_cluster_name }}"
tag_name_kubernetes_private_subnet: "kubernetes-private-subnet-{{ stage }}-{{ aws_cluster_name }}"
tag_name_kubernetes_public_routetable: "kubernetes-public-routetable-{{ stage }}-{{ aws_cluster_name }}"
tag_name_kubernetes_private_routetable: "kubernetes-private-routetable-{{ stage }}-{{ aws_cluster_name }}"


