---
- name: List all hosted zones
  route53_facts:
    region: "{{ ec2_region }}"
    ec2_access_key: "{{ ec2_access_key }}"
    ec2_secret_key: "{{ ec2_secret_key }}"
    query: hosted_zone
  register: hosted_zones

- name: set fact public hosted_zone_id
  set_fact:
    public_hosted_zone_id: "{{ hosted_zones.HostedZones[0].Id | replace('/hostedzone/', '') }}"

- name: set fact private hosted_zone_id
  set_fact:
    private_hosted_zone_id: "{{ hosted_zones.HostedZones[1].Id | replace('/hostedzone/', '') }}"

- name: Gahter ELB Facts
  ec2_elb_facts:
    region: "{{ ec2_region }}"
    ec2_access_key: "{{ ec2_access_key }}"
    ec2_secret_key: "{{ ec2_secret_key }}"
  register: elb_facts

- name: print elb_facts
  debug:
    var: elb_facts

- name: print elb_facts
  debug:
    var: elb_facts.elbs[0].name

- name: print elb_facts
  debug:
    var: elb_facts.elbs[0].hosted_zone_id

- name: print elb_facts
  debug:
    var: elb_facts.elbs[1].name

- name: print elb_facts
  debug:
    var: elb_facts.elbs[1].hosted_zone_id

- name: Create Alias Record to ELB in Public Zone
  route53:
    command: create
    zone: "{{ aws_cluster_name }}"
    ec2_access_key: "{{ ec2_access_key }}"
    ec2_secret_key: "{{ ec2_secret_key }}"
    hosted_zone_id: "{{ public_hosted_zone_id }}"
    record: api.devopscluster.de
    type: A
    value: "{{ item.name }}"
    alias: True
    alias_hosted_zone_id: "{{ item.hosted_zone_id }}"
    alias_evaluate_target_health: False
  with_items: "{{ elb_facts.elbs }}"
  when: '"api" in item.name'