---
- name: List all hosted zones
  route53_facts:
    region: "{{ ec2_region }}"
    ec2_access_key: "{{ ec2_access_key }}"
    ec2_secret_key: "{{ ec2_secret_key }}"
    query: hosted_zone
  register: hosted_zones

- name: set fact public hosted_zone_id
  set_fact:
    public_hosted_zone_id: "{{ hosted_zones.HostedZones[0].Id | replace('/hostedzone/', '') }}"

- name: set fact private hosted_zone_id
  set_fact:
    private_hosted_zone_id: "{{ hosted_zones.HostedZones[1].Id | replace('/hostedzone/', '') }}"

- name: Gahter ELB Facts
  ec2_elb_facts:
    region: "{{ ec2_region }}"
    ec2_access_key: "{{ ec2_access_key }}"
    ec2_secret_key: "{{ ec2_secret_key }}"
  register: elb_facts

- name: print elb_facts
  debug:
    var: elb_facts

- name: Set elb_name
  set_fact:
    elb_name: "{{ elb_facts.elbs|map(attribute='name')|map(attribute='hosted_zone_id')|list }}"

- name: print elb_names
  debug:
    var: elb_name

- name: Create Alias Record to ELB in Public Zone
  route53:
    command: create
    zone: "{{ public_hosted_zone_id }}"
    record: api.devopscluster.de
    type: A
    value: "{{ item }}"
    alias: True
    alias_evaluate_target_health: False
  with_items: "{{ elb_name }}"
  when: '"api" in item'