---
- name: Gather Facts about AWS Kubernetes Cluster
  hosts: localhost
  connection: local
  gather_facts: False
  vars_files:
    - ../vars/credentials.yml
  roles:
    - gather_facts
    - route53_modify