---
- name: Install and Setup Kubernetes on AWS
  hosts: localhost
  connection: local
  gather_facts: False
  vars_files:
    - ../vars/credentials.yml
  roles:
    - gather_facts
    - install_kubernetes
    - route53_modify
    - kubernetes