---
- name: Install and Setup Kubernetes on AWS
  hosts: localhost
  connection: local
  gather_facts: False
  roles:
    - kops
    - kubectl
    - aws_gather_facts
    - kubernetes_provisioning
    - aws_route53_modify
    - kubernetes_validation