---
- name: Install and Setup Kubernetes on AWS
  hosts: localhost
  connection: local
  gather_facts: False
  vars_files:
    - ../vars/credentials.yml
  roles:
    - kops
    - kubectl
    - aws_gather_facts
    - kubernetes_provisioning
    - aws_route53_modify
    - kubernetes_validation
    - kubernetes_user
    - kubernetes_dashboard
    - kubernetes_monitoring
    - kubernetes_external_dns
    - kubernetes_credentials