---
- name: Setup AWS for Kubernetes Install
  hosts: localhost
  connection: local
  gather_facts: False
  vars_files:
    - ../vars/credentials.yml
  roles:
    - keypair
    - virtual_private_cloud
    - route53
    - s3_bucket
    - prepare_localhost
    - install_kubernetes