---
- name: Create new Elastic Loadbalancer for Kubernetes API
  ec2_elb_lb:
    name: "kubernetes-elb-{{ aws_cluster_name }}"
    state: present
    region: "{{ ec2_region }}"
    ec2_access_key: "{{ ec2_access_key }}"
    ec2_secret_key: "{{ ec2_secret_key }}"
    security_group_ids: "{{ sg_elb_id }}"
    subnets: "{{ public_subnet_id }}"
    connection_draining_timeout: 400
    idle_timeout: 400
    listeners:
      - protocol: tcp
        load_balancer_port: 6443
        instance_protocol: tcp
        instance_port: 6443
    tags:
      Name: "kubernetes-elb-{{ aws_cluster_name }}"
      kubernetes.io/cluster/mydevopscluster: "member"
  register: elb