---
###################################
# Variables for AWS
###################################
aws_cluster_name: devopscluster.de
aws_s3_bucket_name: s3://devopsclusterbucket
aws_user: centos
ec2_region: eu-central-1
ec2_keypair: mycentoskeypair

aws_vpc_cidr_block: 10.250.192.0/18
aws_subnet_public:
  - cidr: "10.250.224.0/20"
    availability_zone: eu-central-1a
aws_subnet_private:
  - cidr: "10.250.192.0/20"
    availability_zone: eu-central-1a

tag_name_kubernetes_vpc: "kubernetes-vpc-{{ aws_cluster_name }}"
tag_name_kubernetes_internetgateway: "kubernetes-internetgw-{{ aws_cluster_name }}"
tag_name_kubernetes_public_subnet: "kubernetes-public-subnet-{{ aws_cluster_name }}"
tag_name_kubernetes_private_subnet: "kubernetes-private-subnet-{{ aws_cluster_name }}"
tag_name_kubernetes_public_routetable: "kubernetes-public-routetable-{{ aws_cluster_name }}"
tag_name_kubernetes_private_routetable: "kubernetes-private-routetable-{{ aws_cluster_name }}"


